#!/bin/bash

if [ -z $1 ]; then
	echo provide day plz
	exit
fi
which_day="$1"
tname=`mktemp`
declare -a sessioncookies

try_get_sessioncookie()
{
  cookiesfile="${1}/cookies.sqlite"
  if [ ! -e "$cookiesfile" ]; then return 1; fi
  # Copy the cookies file because file locking shenanigans
  SQL="select value,lastAccessed from moz_cookies where host='.adventofcode.com' and name='session'"
  cp "$cookiesfile" "$tname"
  sqloutput=$(sqlite3 -separator ' ' "$tname" "$SQL")
  rm "$tname"
  read sessioncookie lastaccess <<< "$sqloutput"
  if [ "$sessioncookie" != "" ]; then
    sessioncookies+=( "$cookiesfile $((lastaccess / 1000000)) $sessioncookie" )
  fi
}

MOZ_DIRS=(
  ${HOME}/snap/firefox/common/.mozilla
#  ${HOME}/.mozilla
)

for mozdir in ${MOZ_DIRS[@]}; do
  inifile="${mozdir}/firefox/profiles.ini"
  PATHS=$(git config -f "${mozdir}/firefox/profiles.ini" --get-regexp 'path')
  while read _ path; do
    try_get_sessioncookie "${mozdir}/firefox/${path}"
  done <<< "$PATHS"
done


latest=0
if [ ${#sessioncookies[*]} == 0 ]; then
  echo "Found no valid session cookies in ${MOZ_DIRS[@]}" >&2
  exit 1
elif [ ${#sessioncookies[*]} -gt 1 ]; then
  echo -n "Found multiple firefox profiles with an adventofcode.com session cookie! " >&2
  echo "Selecting the latest of the following:" >&2
  for i in "${sessioncookies[@]}"; do
    read file atime cookie <<< "$i"
    formatteddate=$(date +"%F %H:%M" --date @${atime})
    echo "Access time: $formatteddate Cookies file: $file" >&2
    if [ $atime -gt $latest ]; then
      latest=$atime
      sessioncookie=$cookie
    fi
  done
else
  s=${sessioncookies[0]}
  read _ _ sessioncookie <<< "$s"
fi

curl -b session="$sessioncookie" https://adventofcode.com/2022/day/${which_day}/input

